"""
    gen_RPS_grid(fov::Vector{<:Real}, matrix_size::Vector{<:Real}) -> Array{Float64,4}

Generate a 3D RPS (Read, Phase, Slice) grid of voxel center coordinates.

# Arguments
- `fov`: [m], Field of view, ordered as [FOV_R, FOV_P, FOV_S]
- `matrix_size`: [a.u.], Number of voxels along [R, P, S] axes

# Returns
- A 4D array of shape (nR, nP, nS, 3) where each voxel contains its RPS center coordinate
"""
function gen_RPS_grid(fov::Vector{T}, matrix_size::Vector{D}) where {T <: AbstractFloat, D <: Integer}
    if length(fov) != 3 || length(matrix_size) != 3
        error("Both fov and matrix_size must be 3-element vectors.")
    end

    # Convert to Float64
    fov = T.(fov)
    matrix_size = D.(matrix_size)

    spacing = fov ./ matrix_size

    r = ((0:matrix_size[1]-1) .- (matrix_size[1]-1)/2) .* spacing[1]
    p = ((0:matrix_size[2]-1) .- (matrix_size[2]-1)/2) .* spacing[2]
    s = ((0:matrix_size[3]-1) .- (matrix_size[3]-1)/2) .* spacing[3]

    rr = reshape(r, :, 1, 1)
    pp = reshape(p, 1, :, 1)
    ss = reshape(s, 1, 1, :)

    # Broadcast to form 3D grid
    grid = Array{T, 4}(undef, matrix_size[1], matrix_size[2], matrix_size[3], 3)
    grid[:, :, :, 1] .= rr
    grid[:, :, :, 2] .= pp
    grid[:, :, :, 3] .= ss

    return grid
end

function gen_RPS_grid(geo::Geometry)
    return gen_RPS_grid(geo.FOV, geo.MatrixSize)
end



"""
    RPS2DCS(geo::Geometry, grid_rps::AbstractArray{T, N}) where {T<:Real, N}

Transforms an array of local RPS (Read, Phase, Slice) coordinates to
absolute DCS (Device Coordinate System) physical coordinates using the geometry's spatial mapping.

# Arguments
- `geo`: The `Geometry` structure of the specific slice or slab.
- `grid_rps`: An N-dimensional array where the last dimension holds the 3 coordinate components (R, P, S).
              Usually a 4D array of shape `(Nx, Ny, Nz, 3)` generated by `gen_RPS_grid`.

# Returns
- An array of the exact same shape and element type `T` containing the physical [X, Y, Z] DCS coordinates.
"""
function RPS2DCS(geo::Geometry, grid_rps::AbstractArray{T, N}) where {T<:Real, N}
    size(grid_rps, N) == 3 || error("The last dimension of the grid must be 3 (R, P, S)")

    # 1. Retrieve the pre-calculated rotation matrix and translation vector
    R = Matrix{T}(geo.R_RPS_DCS)
    T_offset = Vector{T}(geo.T_DCS)

    # 2. Flatten the spatial dimensions to shape (K, 3)
    # This allows us to leverage highly optimized BLAS matrix multiplications
    grid_flat = reshape(grid_rps, :, 3)

    # 3. Batch affine transformation: X_DCS = R * X_RPS + T
    # In matrix form for K points: result = grid_flat * R' .+ T_offset'
    result = grid_flat * transpose(R)
    result .+= T_offset'

    # 4. Restore the original array dimensions (e.g., Nx x Ny x Nz x 3)
    return reshape(result, size(grid_rps))
end


"""
    DCS2RPS(geo::Geometry, grid_dcs::AbstractArray{T, N}) where {T<:Real, N}

Transforms an array of absolute DCS (Device Coordinate System) physical coordinates
back to local RPS (Read, Phase, Slice) coordinates for a given Geometry.

# Arguments
- `geo`: The target `Geometry` structure to map into.
- `grid_dcs`: An N-dimensional array where the last dimension holds the 3 coordinate components (X, Y, Z).

# Returns
- An array of the exact same shape and element type `T` containing the logical [R, P, S] coordinates.
"""
function DCS2RPS(geo::Geometry, grid_dcs::AbstractArray{T, N}) where {T<:Real, N}
    size(grid_dcs, N) == 3 || error("The last dimension of the grid must be 3 (X, Y, Z)")

    # 1. Retrieve the pre-calculated rotation matrix and translation vector
    R = Matrix{T}(geo.R_RPS_DCS)
    T_offset = Vector{T}(geo.T_DCS)

    # 2. Flatten the spatial dimensions to shape (K, 3)
    grid_flat = reshape(grid_dcs, :, 3)

    # 3. Inverse affine transformation: X_RPS = R^-1 * (X_DCS - T)
    # Utilizing the orthogonal matrix property: R^-1 = transpose(R)
    # Batch calculation: Result = (grid_flat .- T_offset') * R
    result = (grid_flat .- T_offset') * R

    # 4. Restore the original array dimensions
    return reshape(result, size(grid_dcs))
end


"""
    RPS2PCS(geo::Geometry, grid_rps::AbstractArray{T, N}) where {T<:Real, N}

Transforms an array of local RPS (Read, Phase, Slice) coordinates to
Patient Coordinate System (PCS) anatomical coordinates using the geometry's spatial mapping.

# Arguments
- `geo`: The `Geometry` structure of the specific slice or slab.
- `grid_rps`: An N-dimensional array where the last dimension holds the 3 coordinate components (R, P, S).
              Usually generated by `gen_RPS_grid`.

# Returns
- An array of the exact same shape and element type `T` containing the anatomical [dSag, dCor, dTra] PCS coordinates.
"""
function RPS2PCS(geo::Geometry, grid_rps::AbstractArray{T, N}) where {T<:Real, N}
    size(grid_rps, N) == 3 || error("The last dimension of the grid must be 3 (R, P, S)")

    # 1. Retrieve the pre-calculated rotation matrix and translation vector for PCS
    R = Matrix{T}(geo.R_RPS_PCS)
    T_offset = Vector{T}(geo.T_PCS)

    # 2. Flatten the spatial dimensions to shape (K, 3)
    # This allows us to leverage highly optimized BLAS matrix multiplications
    grid_flat = reshape(grid_rps, :, 3)

    # 3. Batch affine transformation: X_PCS = R * X_RPS + T
    # In matrix form for K points: result = grid_flat * R' .+ T_offset'
    result = grid_flat * transpose(R)
    result .+= T_offset'

    # 4. Restore the original array dimensions
    return reshape(result, size(grid_rps))
end


"""
    PCS2RPS(geo::Geometry, grid_pcs::AbstractArray{T, N}) where {T<:Real, N}

Transforms an array of anatomical PCS (Patient Coordinate System) coordinates
back to local RPS (Read, Phase, Slice) coordinates for a given Geometry.

# Arguments
- `geo`: The target `Geometry` structure to map into.
- `grid_pcs`: An N-dimensional array where the last dimension holds the 3 coordinate components in PCS.

# Returns
- An array of the exact same shape and element type `T` containing the logical [R, P, S] coordinates.
"""
function PCS2RPS(geo::Geometry, grid_pcs::AbstractArray{T, N}) where {T<:Real, N}
    size(grid_pcs, N) == 3 || error("The last dimension of the grid must be 3 (PCS components)")

    # 1. Retrieve the pre-calculated rotation matrix and translation vector for PCS
    R = Matrix{T}(geo.R_RPS_PCS)
    T_offset = Vector{T}(geo.T_PCS)

    # 2. Flatten the spatial dimensions to shape (K, 3)
    grid_flat = reshape(grid_pcs, :, 3)

    # 3. Inverse affine transformation: X_RPS = R^-1 * (X_PCS - T)
    # Utilizing the orthogonal matrix property: R^-1 = transpose(R)
    # Batch calculation: Result = (grid_flat .- T_offset') * R
    result = (grid_flat .- T_offset') * R

    # 4. Restore the original array dimensions
    return reshape(result, size(grid_pcs))
end
